# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter
# at a random position.
# Return the letter that was added to t.

# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"

# Input: Two strings
# Output: A string of letters that was added to the first string.

# Rules:
# - The first string has letters that the second string also have.
# - The second string also contains added letters that the first string does not have.
# - Return those added letters in the second string.

# Algorithm:
# - Split the first string into characters.
# - Iterate through the characters and delete each one of them in the second string.
# - Return the second string.

def find_the_difference(first, second)
  first.chars.each do |char|
    second.sub!(char, '')
  end
  second
end

p find_the_difference("aaa", "abaac") == "bc"
p find_the_difference("", "") == ""
p find_the_difference("abc", "azbscd") == "zsd"
p find_the_difference("", "abc") == "abc"
p find_the_difference("abcde", "") == ""
p find_the_difference("y", "yz") == "z"
p find_the_difference("abc", "abc") == ""
